googleinterns/step87-2020

src/main/java/com/google/sps/servlets/AddTA.java, src/main/webapp/dashboard.css, src/main/webapp/dashboard.html, src/main/webapp/dashboard.js, src/main/webapp/index.html, src/test/java/com/google/sps/servlets/TATest.java
- Addition of TA email form that owner of class uses to add more TAs
- Placeholder chart on right section of dashboard for site stats
=> Create admin dashboard and add TAs to a class

src/main/webapp/workspace/index.html, src/main/webapp/workspace/jitsi.js, src/main/webapp/workspace/workspace.css, src/main/webapp/workspace/workspace.js
Make the tabs drag-able to re-order them.
Move Jitsi code into its own script file for clarity.
=> Minor improvements to workspace

src/main/webapp/workspace/workspace.css, src/main/webapp/workspace/workspace.js
- Update the workspace with a custom color scheme.
- Refactor css to use variables for the colors.
Before:
After:
=> Workspace color theme

src/main/java/com/google/sps/servlets/EnterQueue.java, src/main/java/com/google/sps/servlets/NewClass.java, src/test/java/com/google/sps/servlets/EnterQueueTest.java, src/test/java/com/google/sps/servlets/NewClassTest.java
Create a new visit entity each calendar day.
=> Add visits

src/main/java/com/google/sps/servlets/AddTA.java, src/main/java/com/google/sps/servlets/RequestUtils.java, src/main/webapp/dashboard.css, src/main/webapp/dashboard.html, src/main/webapp/dashboard.js, src/test/java/com/google/sps/servlets/TATest.java
- Resolve merge conflicts from earlier branch
- This branch contains commits that were left out of ta-class from an earlier merge
=> Add TAs to class list

src/main/webapp/firebase-messaging-sw.js, src/main/webapp/queue/student.html, src/main/webapp/queue/ta.html
Send desktop notifications when student is taken off of queue and student is off-page using Firebase Cloud Messaging API.
=> Desktop notifications

src/main/webapp/queue/student.html, src/main/webapp/queue/studentQueue.css, src/main/webapp/queue/ta.html, src/main/webapp/queue/taQueue.css
-Make workspace link open in new tab
-style queue pages
=> Add styling to queue

src/main/java/com/google/sps/workspace/Workspace.java, src/main/webapp/workspace/execution.js, src/test/java/com/google/sps/workspace/WorkspaceTest.java
Synchronizes execution output between all instances of the workspace.
This involves a restructure of the real-time database to include a `timestamp` with each execution.
=> Share executions

src/main/java/com/google/sps/servlets/CheckStudentStatus.java, src/main/java/com/google/sps/servlets/GetQueue.java, src/main/java/com/google/sps/servlets/NotifyStudent.java, src/main/webapp/queue/student.html, src/main/webapp/queue/ta.html, src/test/java/com/google/sps/servlets/GetQueueTest.java, src/test/java/com/google/sps/servlets/NotifyStudentTest.java, src/test/java/com/google/sps/servlets/QueueStatusTest.java
also fixed stream logic when entity not found
=> Create wait entity

rtdb-rules.json, src/main/java/com/google/sps/firebase/FirebaseAppManager.java, src/main/java/com/google/sps/servlets/NotifyStudent.java, src/main/java/com/google/sps/servlets/QueueExecution.java, src/main/java/com/google/sps/tasks/ExecuteCode.java, src/main/java/com/google/sps/workspace/Workspace.java, src/main/java/com/google/sps/workspace/WorkspaceFactory.java, src/main/webapp/workspace/execution.js, src/main/webapp/workspace/index.html, src/main/webapp/workspace/workspace.css, src/test/java/com/google/sps/servlets/NotifyStudentTest.java, src/test/java/com/google/sps/servlets/QueueExecutionTest.java, src/test/java/com/google/sps/tasks/ExecuteCodeTest.java, src/test/java/com/google/sps/workspace/WorkspaceFactoryTest.java, src/test/java/com/google/sps/workspace/WorkspaceTest.java
Add a drop-down to the workspace page that lets a user choose the environment to execute their code.
=> Choose environment

src/main/java/com/google/sps/servlets/EnterQueue.java, src/main/java/com/google/sps/servlets/GetWorkspace.java, src/main/java/com/google/sps/servlets/NotifyStudent.java, src/main/java/com/google/sps/workspace/Workspace.java, src/main/java/com/google/sps/workspace/WorkspaceFactory.java, src/main/webapp/queue/student.html, src/test/java/com/google/sps/servlets/EnterQueueTest.java, src/test/java/com/google/sps/servlets/GetWorkspaceTest.java, src/test/java/com/google/sps/servlets/NotifyStudentTest.java, src/test/java/com/google/sps/workspace/WorkspaceFactoryTest.java, src/test/java/com/google/sps/workspace/WorkspaceTest.java
Gives users access to their workspace as soon as they enter the queue. This will allow them to upload files and choose their environment before a ta can help them.
(Commits from Jul 14 are from a different PR).
=> Early access to workspace

src/main/java/com/google/sps/OnStart.java, src/main/java/com/google/sps/authentication/Authenticator.java, src/main/java/com/google/sps/firebase/FirebaseAppManager.java, src/main/java/com/google/sps/servlets/CheckStudentStatus.java, src/main/java/com/google/sps/servlets/EndHelp.java, src/main/java/com/google/sps/servlets/EnterQueue.java, src/main/java/com/google/sps/servlets/GetQueue.java, src/main/java/com/google/sps/servlets/GetTAHelping.java, src/main/java/com/google/sps/servlets/GetUserData.java, src/main/java/com/google/sps/servlets/NewClass.java, src/main/java/com/google/sps/servlets/NotifyStudent.java, src/main/webapp/WEB-INF/appengine-web.xml, src/main/webapp/WEB-INF/web.xml, src/main/webapp/style/common.css, src/main/webapp/workspace/workspace.css, src/test/java/com/google/sps/authentication/AuthenticatorTest.java, src/test/java/com/google/sps/servlets/EndHelpTest.java, src/test/java/com/google/sps/servlets/EnterQueueTest.java, src/test/java/com/google/sps/servlets/NotifyStudentTest.java
Put firebase constants in environment variables.
Configure datastore only once in  context listener.
=> Refactoring

src/main/java/com/google/sps/servlets/EnterQueue.java, src/main/java/com/google/sps/tasks/TaskScheduler.java, src/main/webapp/dashboard.css, src/main/webapp/dashboard.html, src/main/webapp/homepage.js, src/main/webapp/queue/student.html, src/main/webapp/queue/studentQueue.css, src/main/webapp/userDash.html
- Redirect from login page if user is already signed in
- Put class code on one line on dashboard
- Update dashboard colors
- Remove text shadows on dashboard
- Remove fieldset shadows on dashboard
- Put workspace link underneath place in student queue
https://screenshot.googleplex.com/orsdj24svVn
=> Style changes + redirect

docs/ENVIRONMENT.md, src/main/java/com/google/sps/servlets/EnterQueue.java, src/main/webapp/dashboard.css, src/main/webapp/dashboard.html, src/main/webapp/dashboard.js, src/main/webapp/homepage.css, src/main/webapp/homepage.js, src/main/webapp/index.html, src/main/webapp/queue/student.html, src/main/webapp/queue/ta.html, src/main/webapp/script/auth.js, src/main/webapp/style/common.css, src/main/webapp/userDash.css, src/main/webapp/userDash.html, src/main/webapp/workspace/index.html, src/main/webapp/workspace/workspace.css
Improve UI/UX
- Update background colors.
- Update styling on userDashboard.
- Add logout button to each page.
- Make class buttons squares on the userDaskboard.
- Use tabs for different charts on the dashboard.
=> Ui ux nick

src/main/java/com/google/sps/models/UserData.java, src/main/java/com/google/sps/servlets/user/GetUserData.java, src/main/webapp/dashboard.css, src/main/webapp/dashboard.html, src/main/webapp/queue/student.html, src/main/webapp/queue/ta.html, src/main/webapp/queue/taQueue.css, src/main/webapp/style/common.css, src/main/webapp/userDash.css, src/main/webapp/userDash.html, src/main/webapp/workspace/workspace.css, src/test/java/com/google/sps/servlets/user/GetUserDataTest.java
Add an indicator to the userdash to show students if they are currently in a queue for a class.
Other minor aesthetic changes with fonts, borders around buttons, and tabs in the dashboard.
=> Queue indicator / Aesthetic changes

src/main/java/com/google/sps/models/Environment.java, src/main/java/com/google/sps/servlets/course/EnvironmentServlet.java, src/main/java/com/google/sps/servlets/course/GetEnvironments.java, src/main/java/com/google/sps/tasks/servlets/PullNewEnvironment.java, src/main/webapp/dashboard.js, src/test/java/com/google/sps/servlets/course/EnvironmentServletTest.java, src/test/java/com/google/sps/servlets/course/GetEnvironmentsTest.java, src/test/java/com/google/sps/tasks/servlets/PullNewEnvironmentTest.java
Provide users an error message in an alert if their environment pull fails.
This will be useful for troubleshooting.
=> Environment pull error msg

src/main/webapp/dashboard.css, src/main/webapp/queue/student.js, src/main/webapp/queue/ta.js, src/main/webapp/userDash.html
Fix scrolling on dashboard.
Center form to create class.
Refactor ta and student queue javascript to use a timeout for polling instead of intervals.
=> UI improvements and refactoring timeout

src/main/webapp/queue/ta.js
Update the ta queue page to update the ui before receiving the update via polling. This makes the page more responsive when notifying students and ending help.
=> Make ta queue more responsive

src/main/java/com/google/sps/authentication/Authenticator.java, src/main/java/com/google/sps/servlets/course/DeleteClass.java, src/main/java/com/google/sps/servlets/course/NewClass.java, src/main/java/com/google/sps/servlets/course/RequestAccess.java, src/main/java/com/google/sps/servlets/queue/CheckStudentStatus.java, src/main/java/com/google/sps/servlets/queue/EndHelp.java, src/main/java/com/google/sps/servlets/queue/GetQueue.java, src/main/java/com/google/sps/servlets/queue/NotifyStudent.java, src/main/java/com/google/sps/servlets/queue/RemoveFromQueue.java, src/test/java/com/google/sps/authentication/AuthenticatorTest.java, src/test/java/com/google/sps/servlets/course/AddClassTATest.java, src/test/java/com/google/sps/servlets/course/AddOwnerTest.java, src/test/java/com/google/sps/servlets/course/DeleteClassTest.java, src/test/java/com/google/sps/servlets/course/GetClassNameTest.java, src/test/java/com/google/sps/servlets/course/NewClassTest.java, src/test/java/com/google/sps/servlets/course/ParticipantTest.java, src/test/java/com/google/sps/servlets/course/RequestAccessTest.java, src/test/java/com/google/sps/servlets/course/SubmitRosterTest.java, src/test/java/com/google/sps/servlets/course/VisitByDateTest.java, src/test/java/com/google/sps/servlets/course/WaitTimeTest.java, src/test/java/com/google/sps/servlets/queue/CheckStudentStatusTest.java, src/test/java/com/google/sps/servlets/queue/EndHelpTest.java, src/test/java/com/google/sps/servlets/queue/EnterQueueTest.java, src/test/java/com/google/sps/servlets/queue/GetQueueTest.java, src/test/java/com/google/sps/servlets/queue/NotifyStudentTest.java, src/test/java/com/google/sps/servlets/queue/RemoveFromQueueTest.java, src/test/java/com/google/sps/servlets/user/GetUserDataTest.java, src/test/java/com/google/sps/servlets/user/GetUserRoleTest.java
Authenticate endpoints and remove unused owner property
request-access refactored to give the ability to email multiple owners.
=> Authenticate endpoints

src/main/java/com/google/sps/models/Environment.java, src/main/java/com/google/sps/models/UserData.java, src/main/java/com/google/sps/models/VisitParentDates.java, src/main/java/com/google/sps/models/WaitData.java, src/main/java/com/google/sps/queue/Queue.java, src/main/java/com/google/sps/queue/StudentStatus.java, src/main/java/com/google/sps/servlets/course/AddClassTA.java, src/main/java/com/google/sps/servlets/course/AddOwner.java, src/main/java/com/google/sps/servlets/course/DeleteClass.java, src/main/java/com/google/sps/servlets/course/GetClassName.java, src/main/java/com/google/sps/servlets/course/Participants.java, src/main/java/com/google/sps/servlets/course/SubmitRoster.java, src/main/java/com/google/sps/servlets/queue/CheckStudentStatus.java, src/main/java/com/google/sps/servlets/queue/EndHelp.java, src/main/java/com/google/sps/servlets/queue/EnterQueue.java, src/main/java/com/google/sps/servlets/queue/NotifyStudent.java, src/main/java/com/google/sps/servlets/queue/RemoveFromQueue.java, src/main/java/com/google/sps/servlets/user/GetUserData.java, src/main/java/com/google/sps/servlets/user/GetUserRole.java, src/main/java/com/google/sps/utils/ExceptionWrapper.java, src/main/java/com/google/sps/workspace/WorkspaceFile.java, src/test/java/com/google/sps/servlets/queue/EndHelpTest.java, src/test/java/com/google/sps/servlets/user/GetUserRoleTest.java
Add getters to data models.
Remove unused variables.
Remove unnecessary parenthesis.
=> Resolve PMD issues

src/main/java/com/google/sps/servlets/queue/EnterQueue.java, src/main/java/com/google/sps/servlets/queue/RemoveFromQueue.java, src/test/java/com/google/sps/servlets/queue/EnterQueueTest.java, src/test/java/com/google/sps/servlets/queue/RemoveFromQueueTest.java
prevents adding students to the queue if they're already being helped
lets student leave even if they're currently being helped
=> handling students being helped
